### ISSUE TITLE
Compilation and setup problems against Grid without MPI support

### ISSUE THREAD

**Issue by aragon999** [lehner/gpt#5] opened 2020-04-03 14:12 UTC
In addition to https://github.com/lehner/gpt/issues/4 I also experienced some problems when compiling against a Grid version without MPI support (i.e. the Grid configure flag `--enable-comms=none`).

First I needed to include `mpi.h` in `lib.h` and add mpi to the libs and ldflags. Not sure if this is just missing or part of the underlying problem.

When I try to import `cgpt`, it results in a segfault:
```
python
Python 3.8.2 (default, Feb 26 2020, 22:21:03) 
[GCC 9.2.1 20200130] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cgpt
[1]    28483 segmentation fault (core dumped)  python
```

**Comment by lehner** [comment] 2020-04-04 12:16
I believe this is a duplicate of #4, please check if the fix of #4 also addresses this.

**Closed** 2020-04-04 14:13 UTC
