### ISSUE TITLE
gpt does not respect order of numpy arrays

### ISSUE THREAD

**Issue by krox** [lehner/gpt#59] opened 2020-08-26 15:08 UTC
When writing a numpy array into a gpt object, gpt assumes without checking the standard 'C' memory layout ("row major"). Though this is the default of numpy, it can actually handle arbitrary orders. In particular operators like `numpy.transpose()` avoid moving actual data by simply creating a new view to the data. Here is a simple testcase:

```
# get some arbitrary data
rng = g.random("foo")
grid = g.grid([4,4,4,4], g.double)
foo = rng.normal(g.mcolor(grid))

# compute transpose with numpy and with gpt and check equality
fooT = g.lattice(foo)
fooT[:] = np.transpose(foo[:], (0,2,1))
assert g.norm2(g.adj(foo)-fooT) == 0 # fails in current gpt
```
Its not a huge issue as the workaround is simply writing `tmp = np.copy(tmp, order='C')` before assignment. But I thought I should mention it as it might produce quite subtle bugs for some people.

Some bigger picture: Currently, GPT ignores the shape of the numpy-array completely and just copies raw data, possible multiple times over if the array is smaller than the gpt object. While this does allow intended behavior like
```
foo = g.mcolor(grid)
foo[:] = np.eye(3, dtype=np.complex) # broadcast to all lattice sites
```
it also allows unintended stuff like
```
foo = g.mcolor(grid)
foo[:] = np.array([1.0, 2.0], dtype=np.complex) # some (probably wrong) repeating pattern
```

I think the solution to that would be something like `tmp = np.broadcast_to(tmp, (lattice_sites, *otype.shape))`, which will throw an error if the shapes dont make sense.

(sorry about the long rambling about such a minor issue^^)

**Comment by lehner** [comment] 2020-08-26 15:11
The first issue is known and should be addressed, I will leave this as a TODO and keep the issue open as a reminder.  The second right now is intentional and there may even be a use case for your second example.

Thanks!

**Comment by lehner** [comment] 2020-08-27 10:24
Commit a1b11078e9d8717e006541c82f4385d642a98b20 now adds a check for C ordering on any numpy array that is given to cgpt.  This fixes the most important aspect of this issue, the chance to get unexpected behavior if passing an F ordering array to cgpt.  This leaves only two possible feature requests that we can discuss in a Friday meeting:

1. Should we automatically convert F style to C style if given?  For now the user will be alerted if the wrong ordering is given and he/she has to convert.
2. Is there a reason to modify the generous assignment syntax accepting the repeated patterns?  My preference here is to just document this as a feature such that people can use it if needed.

With this, I would close the issue for now.

**Closed by lehner** 2020-08-27 10:24 UTC

**Comment by lehner** [comment] 2020-08-27 10:29
I should add that since 1 can be performance relevant (maybe a user has the option to create in F or C and in this case should directly create a C style array to avoid an implicit conversion), my preference is to leave it at alerting the user that an incompatible array was given.  It may be good to add to the documentation an explanation how to convert to C ordering.
